import Head from "next/head";

import styles from "../styles/Home.module.scss";
import Deck from "./../components/Deck";

export default function Home() {
  return (
    <>
      <Head>
        <title>Card.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="cards">
        <div className="container">
          <h1>Cards.js</h1>
          <Deck path="cards/" flipped="2">
            <h2>Table</h2>
          </Deck>
          <Deck path="cards/2" flipped="2">
            <h2>Hand</h2>
          </Deck>
        </div>
      </div>
    </>
  );
}
