import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Deck } from "";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Card.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cards">
        <h1>Cards.js</h1>
        <Deck path="table/" flipped="2">
          <h2>Table</h2>
        </Deck>
        <Deck path="deck/2" flipped="2">
          <h2>Hand</h2>
        </Deck>
      </div>
    </div>
  );
}
